#!/bin/bash


# java -Djavax.net.ssl.trustStore=./server/src/main/resources/dev_and_test_truststore.p12 -Djavax.net.ssl.trustStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=ponies

java -jar /keywhiz/cli/target/keywhiz-cli-*-SNAPSHOT-shaded.jar $@
