#!/bin/bash

. /opt/.env

# TODO: get truststore path from ../.ENVj
echo "truststore password is ${TRUSTSTORE_PASSWORD}"
java -Djavax.net.ssl.trustStore=/truststore.p12 -Djavax.net.ssl.trustStorePassword=${TRUSTSTORE_PASSWORD} -jar /keywhiz/cli/target/keywhiz-cli-*-SNAPSHOT-shaded.jar $@
